# Generated by Django 4.0.1 on 2022-01-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
