# Generated by Django 4.0.1 on 2022-01-18 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='slug',
            field=models.SlugField(max_length=384, null=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_campaign', to='api.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
