# Generated by Django 4.0.1 on 2022-01-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('raffle', 'number')},
        ),
    ]
