# Generated by Django 4.0.1 on 2022-01-31 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_raffle_is_finished_raffle_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=10.1, max_digits=6, verbose_name='Preço por ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do prêmio'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do prêmio'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize_name',
            field=models.CharField(max_length=256, verbose_name='Nome do Prêmio'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_prize', to='api.raffle', verbose_name='Rifa'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do sorteio'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Finalizado ?'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='max_number',
            field=models.BigIntegerField(verbose_name='Quantidade Máxima de Ticktes'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='name',
            field=models.CharField(max_length=257, verbose_name='Nome da Rifa'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='raffle_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winner',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ticket vencedor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ticket ativo?'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.BigIntegerField(verbose_name='Número do Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_ticket', to='api.raffle', verbose_name='Rifa'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to=settings.AUTH_USER_MODEL, verbose_name='Usuário detentor'),
        ),
    ]
